models/Statya.php
<?php

namespace app\models;

use Yii;
use yii\helpers\FileHelper;

class Statya extends \yii\db\ActiveRecord {

    public $imageFile = '';

    public static function tableName() {

        return 'statya';

    }

    public function rules() {

        return [
            [['title_ru', 'title_en', 'title_ar', 'title_de', 'title_es', 'title_it', 'short_text_ru', 'short_text_en', 'short_text_ar', 'short_text_de', 'short_text_es', 'short_text_it', 'page_id'], 'required'],
            [['full_text_ru', 'full_text_en', 'full_text_ar', 'full_text_de', 'full_text_es', 'full_text_it'], 'string'],
            [['title_ru', 'title_en', 'title_ar', 'title_de', 'title_es', 'title_it', 'short_text_ru', 'short_text_en', 'short_text_ar', 'short_text_de', 'short_text_es', 'short_text_it', 'image'], 'string', 'max' => 250],
            [['status', 'page_id'], 'integer'],
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg', 'on' => 'create'],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'on' => 'update'],
            [['created_at', 'updated_at'], 'safe'],
        ];

    }

    public function attributeLabels() {

        return [
            'id' => 'ID',
            'title_ru' => 'Title Ru',
            'title_en' => 'Title En',
            'title_ar' => 'Title Ar',
            'title_de' => 'Title De',
            'title_es' => 'Title Es',
            'title_it' => 'Title It',
            'short_text_ru' => 'Short Text Ru',
            'short_text_en' => 'Short Text En',
            'short_text_ar' => 'Short Text Ar',
            'short_text_de' => 'Short Text De',
            'short_text_es' => 'Short Text Es',
            'short_text_it' => 'Short Text It',
            'full_text_ru' => 'Full Text Ru',
            'full_text_en' => 'Full Text En',
            'full_text_ar' => 'Full Text Ar',
            'full_text_de' => 'Full Text De',
            'full_text_es' => 'Full Text Es',
            'full_text_it' => 'Full Text It',
            'image' => 'Image',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
            'page_id' => 'Page',
        ];

    }

    public function upload() {

        if ($this->validate()) {

            $path = 'uploads/statya';

            $name = $path . '/' . rand() . uniqid() . time() . '.' . $this->imageFile->extension;

            FileHelper::createDirectory($path);

            $this->imageFile->saveAs($name);

            if (!empty($this->image)) {

                unlink($this->image);

            }

            $this->image = $name;

            return true;

        } else {

            return false;

        }

    }

    public function beforeSave($insert) {

        if (parent::beforeSave($insert)) {

            if (!isset(Bdata::getPages()[$this->page_id])) {

                $this->page_id = Bdata::PAGE_INDEX;
                
            }
     
            if (!$this->isNewRecord) {

                $this->updated_at = date('Y-m-d H:i:s');

            } else {

                $this->created_at = date('Y-m-d H:i:s');

            }
     
            return true;
        }

        return false;

    }

    public function getTitle() {
        $lan = Yii::$app->language;
        $txt = 'title_'.$lan;
        return $this->$txt;
    }

    public function getShort_text() {
        $lan = Yii::$app->language;
        $txt = 'short_text_'.$lan;
        return $this->$txt;
    }

    public function getFull_text() {
        $lan = Yii::$app->language;
        $txt = 'full_text_'.$lan;
        return $this->$txt;
    }
    
}

controllers/BlogController.php
<?php

namespace app\controllers;

use Yii;
use app\components\NHelper;
use app\models\Bdata;
use app\models\Pagedata;
use app\models\Statya;
use yii\db\Expression;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class BlogController extends Controller {

    public function actionIndex($page = 0) {

        $this->layout = 'layout_blog';

        $lim = 15;

        $cnt = Statya::find()->count();

        $cnt_current = ceil($cnt / $lim);

    	$page = ((int)$page > 0 AND (int)$page <= $cnt_current) ?  (int)$page : 1;

        $off = $lim * ($page - 1);

        $models = Statya::find()->where(['status' => 1])->orderBy(['id' => SORT_DESC])->limit($lim)->offset($off)->all();

        $pagenation = NHelper::createPagenation($cnt_current, $page, 'blog');

        $block1 = Pagedata::byLanAndPage(Bdata::PAGE_CARDS, Bdata::POS_BLOCK1)->one();

        return $this->render('index', ['block1' => $block1, 'models' => $models, 'pagenation' => $pagenation]);

    }

    public function actionItem($id) {
        
        if ($model = Statya::findOne($id)) {

            $this->layout = 'layout_blog_item';

            return $this->render('item', ['model' => $model]);
            
        }

        throw new NotFoundHttpException('The requested page does not exist.');
        
    }

}

views/blog/index.php
<?php 

	use app\components\NHelper;

?>
<section>
	<div class="container">
		<div class="bx-breadcrumb">
			<a href="/"><?=t('Home') ?></a>&raquo; <span><?=t('Blog') ?></span>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row">
		
			<div class="col-sm-12 col-md-4">
				<div class="blog-category">
					<a href="link">Покупка криптовалюты за фиат <ins>(123)</ins></a>
				</div>
			</div>
			<div class="col-sm-12 col-md-4">
				<div class="blog-category">
					<a href="link">Как трейдить криптовалютные пары <ins>(123)</ins></a>
				</div>
			</div>
			<div class="col-sm-12 col-md-4">
				<div class="blog-category">
					<a href="link">Как трейдить криптовалютные пары <ins>(123)</ins></a>
				</div>
			</div>
			<div class="col-sm-12 col-md-4">
				<div class="blog-category">
					<a href="link">Холодные кошельки <ins>(123)</ins></a>
				</div>
			</div>
			<div class="col-sm-12 col-md-4">
				<div class="blog-category active">
					<a href="link">Другое <ins>(123)</ins></a>
				</div>
			</div>
		
		</div>
	</div>
</section>

<section id="articles" class="block articles">
	<div class="container">
		<div class="row">

			<?php if (!empty($models)): ?>

				<?php foreach ($models as $key => $value): ?>

					<div class="col-sm-12 col-md-4">
						<article class="item">
							<a href="/blog-item/<?=$value->id ?>">
								<?php if (!empty($value->image)): ?>
									<img src="/<?=$value->image ?>" />
								<?php endif ?>
							</a>
							<p><a href="/blog-item/<?=$value->id ?>"><?=$value->title ?></a></p>
							<span><a href="/blog-item/<?=$value->id ?>"><?=$value->short_text ?></a></span>
							<a href="/blog-item/<?=$value->id ?>"><?=t('Read more ...') ?></a>
							<ins><?=NHelper::vremya(!empty($value->updated_at) ? $value->updated_at : $value->created_at); ?></ins>
						</article>
					</div>
					
				<?php endforeach ?>
				
			<?php endif ?>

		</div>
	</div>
</section>

<?php if (!empty($pagenation)): ?>

	<section>
		<div class="container">
			<div class="pager">
				<?php foreach ($pagenation as $key2 => $value2): ?>

					<?php if ($value2['active'] == true): ?>

						<span><?=$value2['title'] ?></span>
						
					<?php else: ?>

						<?php if (!empty($value2['link'])): ?>
							
							<a href="<?=$value2['link'] ?>"><?=$value2['title'] ?></a>

						<?php else: ?>

							<a><?=$value2['title'] ?></a>
						
						<?php endif ?>

					<?php endif ?>
					
				<?php endforeach ?>
				<!-- <a href="link">1</a>
				<a href="link">2</a>
				<span>3</span>
				<a>...</a>
				<a href="link">22</a> -->
			</div>
		</div>
	</section>
	
<?php endif ?>

views/blog/item.php
<?php 

use app\models\Bdata;


?>
<section>
	<div class="container">
		<div class="bx-breadcrumb">
			<a href="/"><?=t('Home') ?></a>&raquo; <a href="/blog"><?=t('Blog') ?></a>&raquo; <span><?=$model->title ?></span>
		</div>
	</div>
</section>

<section id="text" class="block text-blog-item" style="padding-top: 0px;">
	<div class="container">
		<h1><?=$model->title ?></h1>
		<?=$model->full_text ?>
	</div>
</section>

<?=$this->render('/layouts/_obzor_stati2', ['p_id' => Bdata::PAGE_BLOG]); ?>